- name: 'Iremocon'
  git: 'git@github.com:katsuma/SiriProxy-iRemocon.git'
  host: '192.168.0.9'
  signals:
      light:
          turn_on: 1000
          turn_off: 1001
      aircon:
          turn_on:   1300
          turn_off:  1301
          heat_up:   1302
          heat_down: 1303
